version: 6

# Configuration for the game settings
game:
  gracePhaseTime: 60  # Duration of the grace phase in seconds
  spectatorSpawnYLavaOffset: 10  # Y offset from the lava where spectators will spawn
  endGameDelay: 5  # Delay in seconds before the game ends
  pvpGracePeriod: 30 # Duration of the grace period for PVP in seconds (set to 0 to disable grace period)

  deathmatch:
    damage: # Configuration for the damage dealt to players during the death match
      enabled: true
      delay: 30
      interval: 20
      amount: 0.5

  lavaRisingTime:
    default: 5  # Default time in seconds for the lava to rise
    levels: # Configuration for the lava rising time based on the Y level (leave empty to use the default time)
      - level: 60
        time: 10
      - level: 70
        time: 15
      - level: 80
        time: 20

  # List of items that players will receive during the game
  items:
    - material: "IRON_AXE"
      amount: 1
      name: "&6Starter Axe"
      lore:
        - "&8A basic axe to chop down trees"
      enchantments:
        - "EFFICIENCY:2"
        - "UNBREAKING:1"
    - material: "IRON_PICKAXE"
      amount: 1
      name: "&6Starter Pickaxe"
      lore:
        - "&8A basic pickaxe to mine ores"
      enchantments:
        - "EFFICIENCY:2"
        - "UNBREAKING:1"

  # Commands to be executed for the winner and players when the game ends
  commands:
    winner:
      - "tell %player% You won the game!"  # Send a congratulatory message to the winner using %winner% placeholder
    losers:
      - "tell %player% You lost the game!"  # Send a message to the players using %player% placeholder
    players: # Commands to be executed for all players (losers and winner)
      - "tell %player% You have been teleported to the lobby!"  # Send a message to the players using %player% placeholder

  visualEffects:
    lava: # Configuration for the lava phase visual effects
      sound:
        enabled: true  # Enable or disable sound effects during the lava phase
        sound: "ENTITY_GENERIC_EXPLODE"  # Sound effect to be played during the lava phase
        volume: 1.0  # Volume of the sound effect
        pitch: 1.0  # Pitch of the sound effect
      title:
        enabled: true  # Enable or disable title messages during the lava phase
        titleMessage: "&6Lava is rising!"  # Title message to be displayed during the lava phase
        subtitleMessage: "&8Get to higher ground!"  # Subtitle message to be displayed during the lava phase
        fadeIn: 10  # Duration of the title fade-in in ticks
        stay: 40  # Duration of the title stay in ticks
        fadeOut: 10  # Duration of the title fade-out in ticks
    pvp: # Configuration for the PVP phase visual effects
      sound:
        enabled: true
        sound: "ENTITY_GENERIC_EXPLODE"
        volume: 1.0
        pitch: 1.0
      title:
        enabled: true
        titleMessage: "&6PVP is enabled!"
        subtitleMessage: "&8Fight to the death!"
        fadeIn: 10
        stay: 40
        fadeOut: 10
    deathmatch: # Configuration for the death match visual effects
      sound:
        enabled: true
        sound: "ENTITY_GENERIC_EXPLODE"
        volume: 1.0
        pitch: 1.0
      title:
        enabled: true
        titleMessage: "&6Death Match!"
        subtitleMessage: "&8Last player standing wins!"
        fadeIn: 10
        stay: 40
        fadeOut: 10
    winner: # Configuration for the sound effect when player wins the game
      sound:
        enabled: true
        sound: "ENTITY_PLAYER_LEVELUP"
        volume: 1.0
        pitch: 1.0
      title:
        enabled: true
        titleMessage: "&6You won!"
        subtitleMessage: "&8Congratulations!"
        fadeIn: 10
        stay: 40
        fadeOut: 10
      particle:
        enabled: true
        particle: "FIREWORKS_SPARK"
        count: 25
        offsetX: 0.5
        offsetY: 0.5
        offsetZ: 0.5
        speed: 0.1
    spectator: # Configuration for the sound effect when player dies and becomes a spectator
      sound:
        enabled: true
        sound: "ENTITY_WITHER_DEATH"
        volume: 1.0
        pitch: 1.0
      title:
        enabled: true
        titleMessage: "&cYou lost!"
        subtitleMessage: "&8Better luck next time!"
        fadeIn: 10
        stay: 40
        fadeOut: 10

# Configuration for the queue settings
queue:
  countdown: 45  # Countdown time in seconds before the game starts
  halfFullQueueCountdown:  # Countdown time when the queue is half full
    enabled: true
    value: 10  # Countdown time in seconds before the game starts when the queue is half full
  leaveItem: # Configuration for the item players use to leave the queue
    material: "BARRIER"
    slot: 8

metrics: true # Enable or disable metrics collection
