name: LavaRise
version: '${project.version}'
main: me.goodbyepavlyi.lavarise.LavaRiseInstance
author: goodbyepavlyi

commands:
  lavarise:
    description: 插件 LavaRise 的主要命令

permissions:
  lavarise.admin:
    default: op
  lavarise.updatechecker:
    default: op
