name: LavaRise
version: '${project.version}'
main: me.goodbyepavlyi.lavarise.LavaRiseInstance
author: goodbyepavlyi
softdepend: ["PlaceholderAPI"]

commands:
  lavarise:
    description: Main command for the plugin LavaRise

permissions:
  lavarise.admin:
    default: op
  lavarise.updatechecker:
    default: op